name: 'DA Release Bot'

runs:
  using: 'composite'
  steps:
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - run: $GITHUB_ACTION_PATH/action.sh
      shell: bash
